DROP DATABASE IF EXISTS `TRAVEL`;

CREATE DATABASE `TRAVEL`;

USE `TRAVEL`;

DROP TABLE IF EXISTS `CAR_PACKAGE`;
CREATE TABLE `CAR_PACKAGE` (
	`CP_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`CP_CR_ID`	INT	NOT NULL,
	`CP_IR_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `CAR`;
CREATE TABLE `CAR` (
	`CR_ID`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`CR_NAME`	VARCHAR(50) NOT	NULL,
	`CR_YEAR`	INT NOT	NULL,
	`CR_FUEL_TYPE`	ENUM("휘발유","경유","하이브리드","전기") NOT	NULL,
	`CR_TRANS`	ENUM("오토","수동") NOT	NULL,
	`CR_TYPE`	VARCHAR(50) NOT	NULL,
	`CR_PRICE`	INT NOT	NULL,
	`CR_COUNT`	INT NOT	NULL,
	`CR_RE_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `LODGING`;
CREATE TABLE `LODGING` (
	`LD_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`LD_NAME`	VARCHAR(100) NOT	NULL,
	`LD_REGION`	VARCHAR(50) NOT	NULL,
	`LD_TYPE`	ENUM("호텔","모텔","펜션") NOT	NULL,
	`LD_NUMBER`	VARCHAR(20) NOT	NULL,
	`LD_RATING`	INT	NULL,
	`LD_INFOR`	LONGTEXT NOT	NULL,
	`LD_MEAL_PRICE`	INT DEFAULT(0)	NULL,
	`LD_ME_NUM`	INT	NOT NULL,
	`LD_RG_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `ROOM`;
CREATE TABLE `ROOM` (
	`RM_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`RM_NAME`	VARCHAR(255) NOT	NULL,
	`RM_PRICE`	INT NOT	NULL,
	`RM_PERSON`	INT NOT	NULL,
	`RM_INFOR`	VARCHAR(255) NOT	NULL,
	`RM_ROOMCOUNT`	INT NOT	NULL,
	`RM_LD_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `THUMBNAIL`;
CREATE TABLE `THUMBNAIL` (
	`TH_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`TH_TABLE`	VARCHAR(20)	NULL,
	`TH_KEY`	INT	NULL,
	`TH_UPLOAD`	VARCHAR(100)	NULL,
	`TH_NAME`	VARCHAR(100)	NULL
);

DROP TABLE IF EXISTS `USER_CHOICE_OPTION`;
CREATE TABLE `USER_CHOICE_OPTION` (
	`UC_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`UC_CO_NUM`	INT	NOT NULL,
	`UC_LR_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `INSURANCEL`;
CREATE TABLE `INSURANCEL` (
	`IR_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`IR_TYPE`	ENUM("대인","대물","X")	NULL,
	`IR_PRICE`	INT NOT	NULL
);

DROP TABLE IF EXISTS `CHOICE_OPTION`;
CREATE TABLE `CHOICE_OPTION` (
	`CO_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`CO_DO_NUM`	INT NOT NULL,
	`CO_TABLE`	VARCHAR(20)	NULL,
	`CO_KEY`	INT	NULL
);

DROP TABLE IF EXISTS `MEMBER`;
CREATE TABLE `MEMBER` (
	`ME_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`ME_ID`	VARCHAR(50) NOT	NULL,
	`ME_PW`	LONGTEXT NOT	NULL,
	`ME_NAME`	VARCHAR(10) NOT	NULL,
	`ME_NICK`	VARCHAR(10) NOT	NULL,
	`ME_NUMBER`	VARCHAR(15)	NULL,
	`ME_EMAIL`	VARCHAR(50) NOT	NULL,
	`ME_AUTHORITY`	ENUM("USER","ADMIN","OWNER") DEFAULT("USER")	NOT NULL,
	`ME_BIRTHDAY`	CHAR(8) NOT NULL,
    `ME_GENDER`	ENUM("남자", "여자")	NULL,
    `ME_PROFILE`	TEXT NULL,
    `ME_DEL`	ENUM("Y", "N")	DEFAULT("N") NOT NULL
);

DROP TABLE IF EXISTS `RE_RESERVATION`;
CREATE TABLE `RE_RESERVATION` (
	`RR_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`RR_CHECKIN`	DATETIME NOT	NULL,
	`RR_CHEKOUT`	DATETIME NOT	NULL,
	`RR_PRICE`	INT NOT	NULL,
	`RR_DATE`	DATETIME NOT	NULL,
	`RR_STATE`	ENUM ("예약완료","예약취소","환불완료") DEFAULT("예약완료") NOT NULL,
	`RR_CP_NUM`	INT	NOT NULL,
	`RR_ME_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `RENTAL`;
CREATE TABLE `RENTAL` (
	`RE_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`RE_NAME`	VARCHAR(20) NOT	NULL,
	`RE_NUMBER`	VARCHAR(20) NOT	NULL,
	`RE_REGION`	VARCHAR(50) NOT	NULL,
	`RE_ME_NUM`	INT	NOT NULL,
	`RE_CT_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `DRIVER_INFOR`;
CREATE TABLE `DRIVER_INFOR` (
	`DI_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`DI_RR_NUM`	INT NOT NULL,
	`DI_NAME`	VARCHAR(10) NOT	NULL,
	`DI_NUMBER`	INT(15) NOT	NULL,
	`DI_BIRTH`	INT(20) NOT	NULL
);

DROP TABLE IF EXISTS `REGION`;
CREATE TABLE `REGION` (
	`RG_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`RG_NAME`	VARCHAR(5) NOT	NULL
);

DROP TABLE IF EXISTS `LO_RESERVATION`;
CREATE TABLE `LO_RESERVATION` (
	`LR_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`LR_CHECKIN`	DATETIME NOT	NULL,
	`LR_CHECKOUT`	DATETIME NOT	NULL,
	`LR_COUNT`	INT NOT	NULL,
	`LR_TOTAL_PRICE`	INT NOT	NULL,
	`LR_STATE`	ENUM("예약완료","예약취소","환불완료") DEFAULT("예약완료")	NOT NULL,
	`LR_DATE`	DATETIME NOT	NULL,
	`LR_BOOKER_NAME`	VARCHAR(100)	NULL,
	`LR_GUEST_NAME`	VARCHAR(100)	NULL,
	`LR_GUEST_NUMBER`	VARCHAR(10)	NULL,
	`LR_CONTENT`	VARCHAR(100)	NULL,
	`LR_MEAL_STATE`	ENUM("Y","N")  DEFAULT("N")	NULL,
	`LR_ME_NUM`	INT	NOT NULL,
	`LR_RM_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `REVIEW`;
CREATE TABLE `REVIEW` (
	`RV_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`RV_RATING`	INT NOT	NULL,
	`RV_CONTENT`	TEXT NOT	NULL,
	`RV_DATE`	DATE NOT	NULL,
	`RV_TABLE_NAME`	VARCHAR(255) NOT	NULL,
	`RV_NUMBER`	INT NOT	NULL,
	`RV_ME_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `DEFAULT_OPTION`;
CREATE TABLE `DEFAULT_OPTION` (
	`DO_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`DO_NAME`	VARCHAR(100)	NULL
);

ALTER TABLE `CAR_PACKAGE` ADD CONSTRAINT `FK_CAR_TO_CAR_PACKAGE_1` FOREIGN KEY (
	`CP_CR_ID`
)
REFERENCES `CAR` (
	`CR_ID`
);

ALTER TABLE `CAR_PACKAGE` ADD CONSTRAINT `FK_INSURANCEL_TO_CAR_PACKAGE_1` FOREIGN KEY (
	`CP_IR_NUM`
)
REFERENCES `INSURANCEL` (
	`IR_NUM`
);

ALTER TABLE `CAR` ADD CONSTRAINT `FK_RENTAL_TO_CAR_1` FOREIGN KEY (
	`CR_RE_NUM`
)
REFERENCES `RENTAL` (
	`RE_NUM`
);

ALTER TABLE `LODGING` ADD CONSTRAINT `FK_MEMBER_TO_LODGING_1` FOREIGN KEY (
	`LD_ME_NUM`
)
REFERENCES `MEMBER` (
	`ME_NUM`
);

ALTER TABLE `LODGING` ADD CONSTRAINT `FK_REGION_TO_LODGING_1` FOREIGN KEY (
	`LD_RG_NUM`
)
REFERENCES `REGION` (
	`RG_NUM`
);

ALTER TABLE `ROOM` ADD CONSTRAINT `FK_LODGING_TO_ROOM_1` FOREIGN KEY (
	`RM_LD_NUM`
)
REFERENCES `LODGING` (
	`LD_NUM`
);

ALTER TABLE `USER_CHOICE_OPTION` ADD CONSTRAINT `FK_CHOICE_OPTION_TO_USER_CHOICE_OPTION_1` FOREIGN KEY (
	`UC_CO_NUM`
)
REFERENCES `CHOICE_OPTION` (
	`CO_NUM`
);

ALTER TABLE `USER_CHOICE_OPTION` ADD CONSTRAINT `FK_LO_RESERVATION_TO_USER_CHOICE_OPTION_1` FOREIGN KEY (
	`UC_LR_NUM`
)
REFERENCES `LO_RESERVATION` (
	`LR_NUM`
);

ALTER TABLE `CHOICE_OPTION` ADD CONSTRAINT `FK_DEFAULT_OPTION_TO_CHOICE_OPTION_1` FOREIGN KEY (
	`CO_DO_NUM`
)
REFERENCES `DEFAULT_OPTION` (
	`DO_NUM`
);

ALTER TABLE `RE_RESERVATION` ADD CONSTRAINT `FK_CAR_PACKAGE_TO_RE_RESERVATION_1` FOREIGN KEY (
	`RR_CP_NUM`
)
REFERENCES `CAR_PACKAGE` (
	`CP_NUM`
);

ALTER TABLE `RE_RESERVATION` ADD CONSTRAINT `FK_MEMBER_TO_RE_RESERVATION_1` FOREIGN KEY (
	`RR_ME_NUM`
)
REFERENCES `MEMBER` (
	`ME_NUM`
);

ALTER TABLE `RENTAL` ADD CONSTRAINT `FK_MEMBER_TO_RENTAL_1` FOREIGN KEY (
	`RE_ME_NUM`
)
REFERENCES `MEMBER` (
	`ME_NUM`
);

ALTER TABLE `RENTAL` ADD CONSTRAINT `FK_REGION_TO_RENTAL_1` FOREIGN KEY (
	`RE_CT_NUM`
)
REFERENCES `REGION` (
	`RG_NUM`
);

ALTER TABLE `DRIVER_INFOR` ADD CONSTRAINT `FK_RE_RESERVATION_TO_DRIVER_INFOR_1` FOREIGN KEY (
	`DI_RR_NUM`
)
REFERENCES `RE_RESERVATION` (
	`RR_NUM`
);

ALTER TABLE `LO_RESERVATION` ADD CONSTRAINT `FK_MEMBER_TO_LO_RESERVATION_1` FOREIGN KEY (
	`LR_ME_NUM`
)
REFERENCES `MEMBER` (
	`ME_NUM`
);

ALTER TABLE `LO_RESERVATION` ADD CONSTRAINT `FK_ROOM_TO_LO_RESERVATION_1` FOREIGN KEY (
	`LR_RM_NUM`
)
REFERENCES `ROOM` (
	`RM_NUM`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `FK_MEMBER_TO_REVIEW_1` FOREIGN KEY (
	`RV_ME_NUM`
)
REFERENCES `MEMBER` (
	`ME_NUM`
);

